version: '2.4'
services:
    jupyter:
        build: 
            context: ../
            dockerfile: .devcontainer/Dockerfile
        restart: 'no'
        volumes:
            - ../:/home/jovyan/notebooks
        ports:
            - "8888:8888"
        # environment:
        #     NB_UID: ${UID}
        #     NB_GID: ${GID}